name: Lint Client and Server

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-client:
    name: Lint Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  lint-server:
    name: Lint Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    env:
      SKIP_DB_PUSH: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --force

      - name: Run linter
        run: npm run lint
